"""site memberships

Revision ID: 15ae373cadf7
Revises: 046d9cf4e891
Create Date: 2026-08-28 22:21:14.492214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ae373cadf7'
down_revision: Union[str, Sequence[str], None] = '046d9cf4e891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'user_id', name='uq_site_members_grain')
    )
    with op.batch_alter_table('site_members', schema=None) as batch_op:
        batch_op.create_index('ix_site_members_user', ['user_id'], unique=False)

    # ### end Alembic commands ###

    # Not autogenerated. Access used to be sites.owner_id alone, and every
    # check now asks this table instead -- so without this line the upgrade
    # takes every existing dashboard away from the person who made it.
    # CURRENT_TIMESTAMP rather than a Python value: both dialects have it, and
    # it keeps the migration free of imports that could drift from the models.
    op.execute(
        sa.text(
            "INSERT INTO site_members (site_id, user_id, role, created_at) "
            "SELECT id, owner_id, 'owner', CURRENT_TIMESTAMP FROM sites"
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_members', schema=None) as batch_op:
        batch_op.drop_index('ix_site_members_user')

    op.drop_table('site_members')
    # ### end Alembic commands ###
