"""bounce counts on the daily grain

Revision ID: 2c70a85ff64d
Revises: 55e312f591f2
Create Date: 2026-08-21 18:51:44.867774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c70a85ff64d'
down_revision: Union[str, Sequence[str], None] = '55e312f591f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounces', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_column('bounces')

    # ### end Alembic commands ###
