"""drop redundant events index

Revision ID: 4115845a588c
Revises: f8fbf94fb7cd
Create Date: 2026-08-19 15:50:29.138472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4115845a588c'
down_revision: Union[str, Sequence[str], None] = 'f8fbf94fb7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_site_timestamp'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_site_timestamp'), ['site_id', 'timestamp'], unique=False)

    # ### end Alembic commands ###
