"""campaign tags

Revision ID: 55e312f591f2
Revises: eb03c7054e15
Create Date: 2026-08-21 14:42:32.223042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e312f591f2'
down_revision: Union[str, Sequence[str], None] = 'eb03c7054e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medium', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('campaign', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('campaign')
        batch_op.drop_column('medium')

    # ### end Alembic commands ###
