"""revenue

Revision ID: c383a4f23cd0
Revises: 15ae373cadf7
Create Date: 2026-08-29 09:54:06.894106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c383a4f23cd0'
down_revision: Union[str, Sequence[str], None] = '15ae373cadf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue_minor', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue_minor', sa.Integer(), nullable=True))

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('revenue_minor')

    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_column('revenue_minor')

    # ### end Alembic commands ###
