"""initial schema

Revision ID: e169c8d7e8dc
Revises: 
Create Date: 2026-08-19 10:19:20.933383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e169c8d7e8dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_salts',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('value', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=253), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('dimension', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'day', 'dimension', 'value', name='uq_daily_stats_grain')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index('ix_daily_stats_lookup', ['site_id', 'dimension', 'day'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=253), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pathname', sa.String(length=1024), nullable=False),
    sa.Column('visitor_id', sa.String(length=32), nullable=False),
    sa.Column('referrer_host', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('os', sa.String(length=64), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_site_timestamp', ['site_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_events_site_visitor', ['site_id', 'timestamp', 'visitor_id'], unique=False)

    op.create_table('hourly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(length=253), nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'hour', name='uq_hourly_stats_grain')
    )
    with op.batch_alter_table('hourly_stats', schema=None) as batch_op:
        batch_op.create_index('ix_hourly_stats_lookup', ['site_id', 'hour'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('users')
    with op.batch_alter_table('hourly_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_hourly_stats_lookup')

    op.drop_table('hourly_stats')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_site_visitor')
        batch_op.drop_index('ix_events_site_timestamp')

    op.drop_table('events')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_stats_lookup')

    op.drop_table('daily_stats')
    op.drop_table('daily_salts')
    # ### end Alembic commands ###
